# Generated by Django 5.2.6 on 2025-09-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('quantity_sold', models.IntegerField()),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank overdraft', 'Bank overdraft')], max_length=50)),
                ('transport_used', models.CharField(blank=True, choices=[('Company_provision', 'Company provision'), ('Self_provision', 'Self provision')], max_length=50)),
                ('date_of_sale', models.DateField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_agent', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('type_of_product', models.CharField(max_length=100)),
                ('costprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateField()),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('measurement', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
