# Generated by Django 5.2.5 on 2025-10-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wood', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
