# Generated by Django 5.2.6 on 2025-09-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Sales Agent', 'Sales Agent')], max_length=50, null=True),
        ),
    ]
