# Generated by Django 5.2.6 on 2025-10-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wood', '0002_alter_add_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Sales Agent', 'Sales Agent')], default='Sales Agent', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='color',
            field=models.CharField(default='blue', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='measurement',
            field=models.CharField(default='0 metres', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplier_name',
            field=models.CharField(max_length=100),
        ),
    ]
